apiVersion : apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      server: nginx


  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
        - name: nginx
          image: app-nginx:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production